#!/bin/bash
if [ -e /usr/bin/msp430 ]; then
    echo "Symlink already exists, skipping."
else
    echo "Creating Symlink in /usr/bin/msp430"
    ln -s /usr/lib/msp430-emu/msp430_emulator /usr/bin/msp430
    ln -s /usr/lib/msp430-emu/msp430_rust /usr/bin/msp430_rust
fi
